" Suchen ohne Gross/Klein
set ignorecase

" Tasten generell
nmap <F5> :wa<CR>
map! <F5> <ESC>:wa<CR>
map <F9> :tabprevious<CR>
map <F10> :tabnext<CR>
" Die just-one-space Funktion von Emacs, direkt auf der Leertaste :-)
nmap <space> :s/[[:space:]]\+\%#[[:space:]]\+/ /e<CR>

" Kaputte Tasten reparieren. Frag mich nicht, warum die manchmal
" nicht gehen
map OH 0
map! OH 0i
map OF $ 
map! OF $a 

syntax on
" colorscheme darkblue
"colorscheme torte
" colorscheme slate
" colorscheme morning


" Einruecken von Python
" set cindent
set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
inoremap # X<BS>#

set cino=g0
map \ :wa<CR>:make -j 8 -z 2>/dev/null ; f12<CR>
map <F12> :wa<CR>:make -j 8 -z 2>/dev/null ; f12<CR>
imap <F12> <ESC>:wa<CR>:make -j 8 -z 2>/dev/null ; f12<CR>

set fileencodings=ucs-bom,utf-8,latin1
set ls=2
set ruler
set showmode
set nocompatible
set sidescroll=1
set sidescrolloff=10
set nolinebreak
set nobackup

set incsearch
set hlsearch
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set ignorecase

" Absatz auf ___ Spalten umbrechen
nmap <C-j> }!{fmt -80 -u<CR>

map! <C-k> <C-o>d$
map! <C-e> <C-o>dw

" Check_MK-Dateien erkennen
autocmd BufRead *.mk set syntax=python filetype=python
autocmd BufRead *.wsgi set syntax=python filetype=python
autocmd BufRead *.twig set syntax=html filetype=html
autocmd BufRead *.lektion set syntax=tex filetype=tex

" Statusbar
set laststatus=2
set statusline=
set statusline+=%-3.3n\                      " buffer number
set statusline+=%f\                          " file name
set statusline+=%h%m%r%w                     " flags
set statusline+=\[%{strlen(&ft)?&ft:'none'}, " filetype
set statusline+=%{&encoding},                " encoding
set statusline+=%{&fileformat}]              " file format
set statusline+=%=                           " right align
set statusline+=0x%-8B\                      " current char
set statusline+=%-10.(%l,%c%V%)\ %<%P        " offset

" Trailing Spaces hervorheben
highlight ExtraWhitespace ctermbg=cyan

highlight IncSearch ctermbg=green guibg=green
highlight Search ctermbg=black ctermfg=white term=bold

" The following alternative may be less obtrusive.
" Show trailing whitespace:
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/

" Show trailing whitespace and spaces before a tab:
match ExtraWhitespace /\s\+$\| \+\ze\t/


" Faltung von wato.py
set foldenable
" map <F7> :set foldlevel=0<CR>
" map <F8> :set foldlevel=1<CR>
" set foldmethod=marker
" set foldmarker=#\ \ \ .,#.
map <F7> :set foldlevel=0<CR>
map <F8> :set foldlevel=1<CR>
" set foldmethod=expr
" set foldexpr=GetPotionFold(v:lnum)

" function! GetPotionFold(lnum)
"     let l = getline(a:lnum)
"     let prev_l = getline(a:lnum-1)
"     if l =~? '^#   \.' " folding at fighead blocks
"         return '>1' " start lvl1 fold
"     elseif a:lnum == 1 && (l =~? '^#!/usr/bin' || l =~? '^// +----' || l =~? '^// .---')
"         " folding at shebang/license blocks
"         return '>1'
"     elseif (prev_l =~? '^[#/]* Boston,' || prev_l =~? '^//  Kettner GmbH') && l =~? '^$'
"         " end license block fold
"         return '0'
"     else
"         return '=' " keep previous fold level
"     endif
" endfunction

" Zeile vom letzten mal merken
autocmd BufReadPost *
 \ if line("'\"") > 0 && line("'\"") <= line("$") |
 \   exe "normal g`\"" |
 \ endif

set nocompatible              " be iMproved, required

" Markieren langer zeilen
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%101v', 100)

